[package]
name = "mediasoup"
version = "0.6.0"
description = "Cutting Edge WebRTC Video Conferencing in Rust"
categories = ["api-bindings", "multimedia", "network-programming"]
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2018"
license = "ISC"
keywords = ["webrtc", "ortc", "sfu"]
documentation = "https://docs.rs/mediasoup"
repository = "https://github.com/versatica/mediasoup/tree/v3/rust"
readme = "readme.md"

[dependencies]
async-channel = "1.5.1"
async-executor = "1.4.0"
async-fs = "1.5.0"
async-io = "1.3.1"
async-lock = "2.3.0"
async-oneshot = "0.4.2"
async-process = "1.0.1"
async-trait = "0.1.42"
bytes = "1.0.0"
event-listener-primitives = "0.2.2"
fastrand = "1.4.0"
futures-lite = "1.11.3"
h264-profile-level-id = "0.1.1"
log = "0.4.11"
libc = "0.2.82"
nix = "0.19.1"
once_cell = "1.5.2"
serde_json = "1.0.61"
serde_repr = "0.1.6"
thiserror = "1.0.23"

[dependencies.lru]
default-features = false
version = "0.6.5"

[dependencies.parking_lot]
version = "0.11.1"
features = ["serde"]

[dependencies.regex]
default-features = false
features = ["std", "perf"]
version = "1.4.2"

[dependencies.serde]
features = ["derive"]
version = "1.0.118"

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.8.1"

[dev-dependencies]
actix = "0.10.0"
actix-web = "3.3.2"
actix-web-actors = "3.0.0"
env_logger = "0.8.2"
