name: Sync with upstream releases

on:
  workflow_dispatch:
    inputs:
  #schedule:
  #  - cron:  '0 2 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git log
